version: "3.8"

services:
    crawler_yahoo:
        environment:
          REGION: 'Argentina'
          PATH_SAVE: '/app/src/'
          PYTHONUNBUFFERED: 1
        container_name: crawler_yahoo
        volumes:
          - ./src:/app/src
        build: .
        entrypoint: ["python", "/app/main.py"]
