version: "3.8"

services:
    crawler_yahoo:
        environment:
          REGION: 'Brazil'
          PATH_SAVE: '/app/src/'
          PYTHONUNBUFFERED: 1
          USERNAME_LOGIN: 'victorarruda2023@yahoo.com'
          PASSWORD_LOGIN: 'NovaSenha123!!'
        container_name: crawler_yahoo
        volumes:
          - ./src:/app/src
        build: .
        entrypoint: ["python", "/app/main.py"]
